ceph: adding '--upgrade' option to the script
openshift/rook pull request #134
Opened 2020-10-12 15:24 UTC by aruniiird

**Description of your changes:**
An '--upgrade' option is added to the option list, which upgrades the
user permissions (caps) to match newer version. Will try to detect
'rgw-pool-prefix' or user can provide it through the argument.

Segregated the command line arguments into three groups - common, output
and upgrade

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-10-12 15:37 UTC, leseb requested changes
Use `cherry-pick -x`  to cherry-pick the commit. Also add a bug number

2020-10-13 10:16 UTC, aruniiird commented
> Use `cherry-pick -x` to cherry-pick the commit. Also add a bug number

@leseb , made the changes, please take a look...

2020-10-13 10:17 UTC, leseb requested changes
You did not use `git cherry-pick -x`...

2020-10-13 10:38 UTC, leseb approved these changes

2020-10-13 10:38 UTC, merged